version: '3'
services:
  jupyter:
    build: .
    volumes:
      - './src:/project/src'
      - './src:/project/notebook/module'
      - './img:/project/img'
      - './notebook:/project/notebook'
      - './data:/project/data'
    ports:
      - '8888'
    env_file:
      - './jupyter.env'
      - './db.env'
    depends_on:
      - db
  db:
    image: 'postgres:9.6.2'
    volumes:
      - './db:/var/lib/postgresql/data'
    env_file:
      - './db.env'
    ports:
      - '5432'
